adding additional options and improving opts/args parsing

diff --git a/pkgr b/pkgr
--- a/pkgr
+++ b/pkgr
@@ -1,10 +1,19 @@
 #!/bin/bash
 
+OK=0
+INVALID_OPTS=1
+INVALID_PKGTYPE=2
+INVALID_PARAMS=3
+NO_DESCRIPTION=4
+OTHER_ERROR=127
+
 [[ -n $DEBUG ]] && DEBUG=$DEBUG || DEBUG=0
 
 die()
 {
+    local exit_code=$OTHER_ERROR
     local frame=0
+    [[ -n $2 ]] && exit_code=$2
 
     echo "$*"
 
@@ -14,7 +23,7 @@ die()
         done
     fi
 
-    exit 1
+    exit $exit_code
 }
 
 usage()
@@ -30,6 +39,13 @@ OPTIONS:
  -t[package type]|--type[=package type] 	Specify the package type, either 'rpm' or 'deb'
  -n|--new                                       Build a first release package
  -d|--description                               Description of the project
+ --dependencies='dep1, dep2, ...'               Comma seperated list of runtime dependencies
+ --build-deps='dep1, dep2, ...'                 Comma seperated list of build dependencies
+ --packager-name=<packager_name>                Name of the package maintainer
+ --packager-email=<packager_email>              Email address of the package maintainer
+ -i<iteration>|--iteration=<iteration>          The package revision
+ --rules-file                                   The file to use for debian/rules (for overriding buildsystem sequences -- only debian)
+ --install-file                                 List of files to install (debian only -- see man pkgr for example)
 
 PARAMETERS:
  project_name                                   The name of the project (as it is in the VCS)
@@ -37,11 +53,6 @@ PARAMETERS:
 
 EOF
 }
-
-if [ $# -lt 2 ]; then
-    echo 'At least two parameters are required (project_name and version_string).'
-    usage; exit 1
-fi
 
 if [[ $DEBUG -eq 1 ]]; then
     ARGS=`getopt -o t::ndh --long type::,new,description:,help -n "$0" -- "$@"`
@@ -62,24 +73,34 @@ while true; do
             case "$2" in
                 ""|deb|debian) PKGTYPE='deb'; shift 2;;
                 rpm) PKGTYPE='rpm'; shift 2;;
-                *) echo "Invalid package type. See $0 -h for more info."; exit 2;;
+                *)
+                    echo "Invalid package type. See $0 -h for more info.";
+                    exit $INVALID_PKGTYPE
+                    ;;
             esac ;;
         -n|--new)
             IS_NEW=1; shift;;
         -d|--description)
             DESCRIPTION="$2"; shift 2;;
         -h|--help)
-            usage; exit 1;;
+            usage; exit $OK;;
         --)
             shift;
-            # we don't break here because we expect two additional parameters.
-            #break
+            break
             ;;
         *)
-            the_rest=$@
+            usage;
+            exit $INVALID_OPTS;
             break;;
     esac
 done
+
+the_rest=$@
+
+if [ $# -lt 2 ]; then
+    echo 'At least two parameters are required (project_name and version_string).'
+    usage; exit $INVALID_OPTS
+fi
 
 # Split the remaining parameters by space and into an array.
 IFS=' ' read -a PARAMS <<< "$the_rest"
@@ -100,11 +121,11 @@ if [ ${#PARAMS[@]} -gt 2 ]; then
         invalid_params="${invalid_params} ${PARAMS[index]}"
     done
     echo "${invalid_params}"
-    usage; exit 1
+    usage; exit $INVALID_PARAMS
 # Insufficient number of parameters detected
 elif [ "${#PARAMS[@]}" -lt 2 ]; then
     echo 'At least two parameters are required (project_name and version_string).'
-    usage; exit 1
+    usage; exit $INVALID_PARAMS
 # The remaining arguments should represent the project and the version to be packaged.
 # Attempt to capture the project name and version string regardless of their order.
 else
@@ -122,7 +143,7 @@ if [ -n "${version_string}" -a -n "${project_name}" ]; then
     # validate string provided as project name
     if [[ ! "${project_name}" =~ ^([A-Za-z0-9._-])+$ ]]; then
         echo "The project name \"${project_name}\" seems to be invalid"
-        exit 3
+        exit $INVALID_PARAMS
     fi
 else
     # If version_string is zero-length then it was not matched previously.
@@ -132,7 +153,7 @@ else
         echo 'unable to determine project name'
     fi
     usage
-    exit 3
+    exit $INVALID_PARAMS
 fi
 
 if [ $IS_NEW -eq 1 ]; then
@@ -140,7 +161,7 @@ if [ $IS_NEW -eq 1 ]; then
     if [ -z "${DESCRIPTION}" ]; then
         # TODO: read descript from input
         echo 'A description is necessary'
-        exit 4
+        exit $INVALID_PARAMS
     fi
 fi
 
